config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  get 'users/show'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: "evetts#index"
  resources :evetts do
    resources :payments, only: [:index, :create]
  end
  resources :users, only: [:show, :update] do
    resources :cards, only: [:new, :create]
    get 'followings', to: 'freinds#followings', as: 'followings'
    get 'followeds', to: 'freinds#followeds', as: 'followeds'
    resource :friend, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
end

app/models/evett.rb
class Evett < ApplicationRecord
  with_options presence: true do
    validates :name
    validates :text
    validates :price, numericality: { greater_than: 299, less_than: 10_000_000 }
  end

  belongs_to :user
  has_many :payments, dependent: :destroy
end

app/controllers/evetts_controller.rb
class EvettsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :edit, :show]
  before_action :evett_find, only: [:show, :edit, :update, :destroy]
  before_action :unless_user_id, only: [:edit, :destroy]

  def index
    @evetts_all = Evett.where(share_area_id: 1).order('created_at DESC')
    @evetts_friend = Evett.where(share_area_id: 2).order('created_at DESC')
    @evetts_only = Evett.where(share_area_id: 3).order('created_at DESC')

    @followed_users = current_user.followed_user
  end

  def new
    @evett = Evett.new
  end

  def create
    @evett = Evett.new(evett_params)
    evett_size = Evett.where(user_id: @evett.user_id).size
    if @evett.valid?
      if @evett.user.rank_id == 1 
        if evett_size <= 5
          @evett.save
          redirect_to root_path, notice: "投稿を保存しました"
        else
          redirect_to root_path, notice: "ブロンズランクの投稿数は５までです"
        end
      elsif @evett.user.rank_id == 2
        if evett_size <= 10
          @evett.save
          redirect_to root_path, notice: "投稿を保存しました"
        else
          redirect_to root_path, notice: "シルバーランクの投稿数は10までです"
        end
      elsif @evett.user.rank_id == 3
        if evett_size <= 50
          @evett.save
          redirect_to root_path, notice: "投稿を保存しました"
        else
          redirect_to root_path, notice: "ゴールドランクの投稿数は50までです"
        end
      end
    else
      render :new
    end
  end

  def show
    @payment = Payment.where(evett_id: @evett.id).sum(:pay)
    
    if @evett.share_area_id == 3
      redirect_to root_path unless @evett.user.id == current_user.id
    elsif @evett.share_area_id == 2 
      if current_user.following_user.find_by(id: @evett.user.id) != nil
        redirect_to root_path unless @evett.user.id == current_user.id
      end
    end
  end

  def edit
    session[:previous_url] = request.referer
  end

  def update
    if @evett.update(evett_params)
      redirect_to session[:previous_url]
    else
      render :edit
    end
  end

  def destroy
    @evett.destroy
    redirect_to request.referrer || root_path
  end

  private

  def evett_params
    params.require(:evett).permit(:name, :text, :price, :limit_date, :share_area_id).merge(user_id: current_user.id)
  end

  def evett_find
    @evett = Evett.find(params[:id])
  end

  def unless_user_id
    redirect_to root_path unless current_user.id == @evett.user_id
  end
end

app/helpers/evetts_helper.rb
module EvettsHelper
end

app/views/evetts/edit.html.erb
<div class="main">
  <div class='transaction-contents'>
    <div class='logo'><%= link_to "Evett", root_path %></div>
    <div class='transaction-main'>
      <h2 class="evetts-sell-title">evettの情報を入力</h2>
      <%= form_with model: @evett, local: true do |f| %>

      <%= render 'shared/error_messages', model: f.object %>

      <%# evett名とevett説明 %>
      <div class="new-evetts">
        <div class="weight-bold-text">
          evett名
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :name, class:"evetts-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
        <div class="evetts-explain">
          <div class="weight-bold-text">
            evettの説明
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :text, class:"evetts-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）例）NIKEの最新スニーカーを買う" ,rows:"7" ,maxlength:"1000" %>
        </div>
      </div>
      <%# /evett名とevett説明 %>

      <%# evett詳細について %>
      <div class="evetts-detail">
        <div class="form">
          <div class="weight-bold-text">
            公開範囲の設定
          </div>
          <%= f.collection_select(:share_area_id, ShareArea.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
          <div class="form-area">
            <div class='form-text-wrap'>
              <label class="form-text">目標日</label>
              <%= f.date_field(:limit_date, value: Time.now.strftime("2022Y-1m-1d")) %>
              <% unless @evett.limit_date.blank? %>
                <p>＊<%= @evett.limit_date %>が現在入力されています。入力してください。</p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <%# /evett詳細について %>

      <%# 販売価格 %>
      <div class="sell-price">
        <div class="weight-bold-text question-text">
          <span>設定価格<br>(¥300〜9,999,999)</span>
          <a class="question" href="#">?</a>
        </div>
          <div class="price-content">
            <div class="price-text">
              <span>価格</span>
              <span class="indispensable">必須</span>
            </div>
            <span class="sell-yen">¥</span>
            <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
          </div>
      </div>
      <%# /販売価格 %>

      <%# 注意書き %>
      <div class="caution">
        <p class="sentence">
          <a href="#">禁止されている出品、</a>
          <a href="#">行為</a>
          を必ずご確認ください。
        </p>
      </div>
      <%# /注意書き %>
      <%# 下部ボタン %>
      <div class="sell-btn-contents">
        <%= f.submit "投稿する" ,class:"sell-btn" %>
        <%=link_to 'もどる', root_path, class:"back-btn" %>
      </div>
      <%# /下部ボタン %>
    </div>
    <% end %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/evetts/index.html.erb
<%= render "shared/evett-header" %>

<div class='main'>
  <%# evett一覧 %>
  <div class='active-evett' id="all">
    <% @evetts_all.each do |evett|%>
      <li class='evett_content'>
        <div class='evett_area' >
          <ul class='content_menu'>
            <% if evett.user_id == current_user.id %>
              <li>
                <%= link_to "編集", edit_evett_path(evett.id), method: :get %>
              </li>
              <li>
                <%= link_to "削除", evett_path(evett.id), method: :delete %>
              </li>
            <% end %>
          </ul>
          <%= link_to evett_path(evett.id) do %>
            <div class='main_content'>
              <div class='evett_name'>
                <h2><%= evett.name %></h2>
              </div>
              <div class='evett_limit_date'>
                <% if evett.limit_date.present? %>
                  <h2>目標日：<%= evett.limit_date %></h2>
                <% end %>
              </div>
              <div class='evett_price_back'>
                <h2 class="evett_price"><%= Payment.where(evett_id: evett.id).sum(:pay) %>/<%= evett.price %>円</h2>
                <% if Payment.where(evett_id: evett.id).sum(:pay) * 100 / evett.price >= 100 %>
                  <div id="max_percentage", class='evett_price_bar' style="width: 100%;"></div>
                <% else %>
                  <div class='evett_price_bar' style="width: <%=  Payment.where(evett_id: evett.id).sum(:pay) * 100 / evett.price %>%;"></div>
                <% end %>
              </div>
              <div class='payment_area'>
                <%= link_to evett_payments_path(evett.id) do %>
                  <div class='evett_payment_btn'>入金</div>
                <% end %>
                <div class='payment_percentage'>
                  <% unless Payment.where(evett_id: evett.id).sum(:pay) == 0 %>
                    <h2><%= Payment.where(evett_id: evett.id).sum(:pay) * 100 / evett.price %>%</h2>
                  <% else %>
                    <h2>0%</h2>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </li>
    <% end %>
  </div>
  <div class='not-active-evett' id="friend">
    <% @evetts_friend.each do |evett|%>
      <% if @followed_users.find_by(id: evett.user_id) != nil || evett.user.id == current_user.id %>
        <li class='evett_content'>
          <div class='evett_area' >
            <ul class='content_menu'>
              <% if evett.user_id == current_user.id %>
                <li>
                  <%= link_to "編集", edit_evett_path(evett.id), method: :get %>
                </li>
                <li>
                  <%= link_to "削除", evett_path(evett.id), method: :delete %>
                </li>
              <% end %>
            </ul>
            <%= link_to evett_path(evett.id) do %>
              <div class='main_content'>
                <div class='evett_name'>
                  <h2><%= evett.name %></h2>
                </div>
                <div class='evett_limit_date'>
                  <% if evett.limit_date.present? %>
                    <h2>目標日：<%= evett.limit_date %></h2>
                  <% end %>
                </div>
                <div class='evett_price_back'>
                  <h2 class="evett_price"><%= Payment.where(evett_id: evett.id).sum(:pay) %>/<%= evett.price %>円</h2>
                  <% if Payment.where(evett_id: evett.id).sum(:pay) * 100 / evett.price >= 100 %>
                    <div id="max_percentage", class='evett_price_bar' style="width: 100%;"></div>
                  <% else %>
                    <div class='evett_price_bar' style="width: <%=  Payment.where(evett_id: evett.id).sum(:pay) * 100 / evett.price %>%;"></div>
                  <% end %>
                </div>
                <div class='payment_area'>
                  <%= link_to evett_payments_path(evett.id) do %>
                    <div class='evett_payment_btn'>入金</div>
                  <% end %>
                  <div class='payment_percentage'>
                    <% unless Payment.where(evett_id: evett.id).sum(:pay) == 0 %>
                      <h2><%=  Payment.where(evett_id: evett.id).sum(:pay) * 100 / evett.price %>%</h2>
                    <% else %>
                      <h2>0%</h2>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </li>
      <% end %>
    <% end %>
  </div>
  <div class='not-active-evett' id="user">
    <% @evetts_only.each do |evett|%>
      <% if evett.user.id != current_user.id %>
      <% else %>
        <li class='evett_content'>
          <div class='evett_area' >
            <ul class='content_menu'>
              <% if evett.user_id == current_user.id %>
                <li>
                  <%= link_to "編集", edit_evett_path(evett.id), method: :get %>
                </li>
                <li>
                  <%= link_to "削除", evett_path(evett.id), method: :delete %>
                </li>
              <% end %>
            </ul>
            <%= link_to evett_path(evett.id) do %>
              <div class='main_content'>
                <div class='evett_name'>
                  <h2><%= evett.name %></h2>
                </div>
                <div class='evett_limit_date'>
                  <% if evett.limit_date.present? %>
                    <h2>目標日：<%= evett.limit_date %></h2>
                  <% end %>
                </div>
                <div class='evett_price_back'>
                  <h2 class="evett_price"><%= Payment.where(evett_id: evett.id).sum(:pay) %>/<%= evett.price %>円</h2>
                  <% if Payment.where(evett_id: evett.id).sum(:pay) * 100 / evett.price >= 100 %>
                    <div id="max_percentage", class='evett_price_bar' style="width: 100%;"></div>
                  <% else %>
                    <div class='evett_price_bar' style="width: <%=  Payment.where(evett_id: evett.id).sum(:pay) * 100 / evett.price %>%;"></div>
                  <% end %>
                </div>
                <div class='payment_area'>
                  <%= link_to evett_payments_path(evett.id) do %>
                    <div class='evett_payment_btn'>入金</div>
                  <% end %>
                  <div class='payment_percentage'>
                    <% unless Payment.where(evett_id: evett.id).sum(:pay) == 0 %>
                      <h2><%=  Payment.where(evett_id: evett.id).sum(:pay) * 100 / evett.price %>%</h2>
                    <% else %>
                      <h2>0%</h2>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </li>
      <% end %>
    <% end %>
  </div>
  <%# /evett一覧 %>
  <%= link_to(new_evett_path, class: 'purchase-btn') do %>
    <span class='purchase-btn-text'>投稿する</span>
  <% end %>
</div>

<%= render "shared/footer" %>

app/views/evetts/new.html.erb
<div class="main">
  <div class='transaction-contents'>
    <div class='logo'><%= link_to "Evett", root_path %></div>
    <div class='transaction-main'>
      <h2 class="evetts-sell-title">evettの情報を入力</h2>
      <%= form_with model: @evett, local: true do |f| %>

      <%= render 'shared/error_messages', model: f.object %>

      <%# evett名とevett説明 %>
      <div class="new-evetts">
        <div class="weight-bold-text">
          evett名
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :name, class:"evetts-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
        <div class="evetts-explain">
          <div class="weight-bold-text">
            evettの説明
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :text, class:"evetts-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）例）NIKEの最新スニーカーを買う" ,rows:"7" ,maxlength:"1000" %>
        </div>
      </div>
      <%# /evett名とevett説明 %>

      <%# evett詳細について %>
      <div class="evetts-detail">
        <div class="form">
          <div class="weight-bold-text">
            公開範囲の設定
          </div>
          <%= f.collection_select(:share_area_id, ShareArea.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
          <div class="form-area">
            <div class='form-text-wrap'>
              <label class="form-text">目標日</label>
              <%= f.date_field(:limit_date, value: Time.now.strftime("2022Y-1m-1d")) %>
            </div>
          </div>
        </div>
      </div>
      <%# /evett詳細について %>

      <%# 販売価格 %>
      <div class="sell-price">
        <div class="weight-bold-text question-text">
          <span>設定価格<br>(¥300〜9,999,999)</span>
          <a class="question" href="#">?</a>
        </div>
          <div class="price-content">
            <div class="price-text">
              <span>価格</span>
              <span class="indispensable">必須</span>
            </div>
            <span class="sell-yen">¥</span>
            <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
          </div>
      </div>
      <%# /販売価格 %>

      <%# 注意書き %>
      <div class="caution">
        <p class="sentence">
          <a href="#">禁止されている出品、</a>
          <a href="#">行為</a>
          を必ずご確認ください。
        </p>
      </div>
      <%# /注意書き %>
      <%# 下部ボタン %>
      <div class="sell-btn-contents">
        <%= f.submit "投稿する" ,class:"sell-btn" %>
        <%=link_to 'もどる', root_path, class:"back-btn" %>
      </div>
      <%# /下部ボタン %>
    </div>
    <% end %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/evetts/show.html.erb
<%= render "shared/header" %>
<div class="main">
  <%# evettの概要 %>
  <div class='evett_show'>
    <div class='evett_show_area' >
      <ul class='show_content_menu'>
        <% if @evett.user_id == current_user.id %>
          <li>
            <%= link_to "編集", edit_evett_path(@evett.id), method: :get %>
          </li>
          <li>
            <%= link_to "削除", evett_path(@evett.id), method: :delete %>
          </li>
        <% end %>
      </ul>
      <div class='show_main_content'>
        <div class='evett_show_name'>
          <h2><%= @evett.name %></h2>
          <h1><%= link_to @evett.user.nickname, user_path(@evett.user.id), method: :get %> </h1>
        </div>
        <div class='evett_show_box'>
          <%= @evett.text %>
        </div>
        <div class='evett_show_limit_date'>
          <% if @evett.limit_date.present? %>
            <h2>目標日：<%= @evett.limit_date %></h2>
          <% end %>
        </div>
        <div class='evett_show_price_back'>
          <h2 class="evett_price"><%= Payment.where(evett_id: @evett.id).sum(:pay) %>/<%= @evett.price %>円</h2>
          <% if Payment.where(evett_id: @evett.id).sum(:pay) * 100 / @evett.price >= 100 %>
            <div id="max_percentage", class='evett_price_bar' style="width: 100%;"></div>
          <% else %>
            <div class='evett_price_bar' style="width: <%=  Payment.where(evett_id: @evett.id).sum(:pay) * 100 / @evett.price %>%;"></div>
          <% end %>
        </div>
        <div class='evett_show_payment_area'>
          <%= link_to evett_payments_path(@evett.id) do %>
            <div class='evett_show_payment_btn'>入金</div>
          <% end %>
          <div class='evett_show_payment_percentage'>
            <% unless Payment.where(evett_id: @evett.id).sum(:pay) == 0 %>
              <h2><%=  Payment.where(evett_id: @evett.id).sum(:pay) * 100 / @evett.price %>%</h2>
            <% else %>
              <h2>0%</h2>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render "shared/second-footer" %>