config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  get 'users/show'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: "evetts#index"
  resources :evetts do
    resources :payments, only: [:index, :create]
  end
  resources :users, only: [:show, :update] do
    resources :cards, only: [:new, :create]
    get 'followings', to: 'freinds#followings', as: 'followings'
    get 'followeds', to: 'freinds#followeds', as: 'followeds'
    resource :friend, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :following, class_name: 'User'
  belongs_to :followed, class_name: 'User'

  validates :followed_id, presence: true
  validates :following_id, presence: true
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def create
    @user = current_user
    following_size = @user.following.size
    if @user.rank_id == 1
      if following_size < 10
        current_user.follow(params[:user_id])
        redirect_to request.referer, notice: "フォローしました"
      else
        redirect_to request.referer, notice: "ブロンズランクのフォロー上限は10人です"
      end
    elsif @user.rank_id == 2
      if following_size < 30
        current_user.follow(params[:user_id])
        redirect_to request.referer, notice: "フォローしました"
      else
        redirect_to request.referer, notice: "シルバーランクのフォロー上限は30人です"
      end
    elsif @user.rank_id == 3
      if following_size < 100
        current_user.follow(params[:user_id])
        redirect_to request.referer, notice: "フォローしました"
      else
        redirect_to request.referer, notice: "ゴールドランクのフォロー上限は100人です"
      end
    end
    
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_follow.html.erb
<div class="follow-list">
  <div class="follow-title">
    友達一覧
  </div>
  <div class="follow-area">
    <div class="follow", id="followed-area">
      <% @followed_users.each do |followed| %>
        <div class="follow_name">
          <%= link_to followed.nickname, user_path(followed.id), method: :get %>
          <%= link_to "解除", user_friend_path(followed.id), method: :delete, class: "follow_name_btn" %>
        </div>
      <% end %>
    </div>
    <div class="follow", id="following-area">
      <% @following_users.each do |following| %>
        <div class="follow_name">
          <%= link_to following.nickname, user_path(following.id), method: :get %>
          <%= link_to "解除", user_friend_path(following.id), method: :delete, class: "follow_name_btn" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="follow_num">
    <h5 id="following">フォロー<%= user.following.count %>人（閲覧可能）</h5>
    <h5 id="followed">フォロワー<%= user.followed.count %>人（閲覧許可）</h5>
  </div>
</div>

app/views/friends/_follow_btn.html.erb
<% if current_user.following?(user_id) %>
  <%= link_to "フォロー解除", user_friend_path(user_id), method: :delete, class: "follow_btn" %>
<% else %>
  <%= link_to "フォローする", user_friend_path(user_id), method: :post, class: "follow_btn" %>
<% end %>