config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  get 'users/show'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: "evetts#index"
  resources :evetts do
    resources :payments, only: [:index, :create]
  end
  resources :users, only: [:show, :update] do
    resources :cards, only: [:new, :create]
    get 'followings', to: 'freinds#followings', as: 'followings'
    get 'followeds', to: 'freinds#followeds', as: 'followeds'
    resource :friend, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  validates :nickname, presence: true
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください'

  has_many :evetts, dependent: :destroy
  has_many :payments, dependent: :destroy
  has_one :card, dependent: :destroy
  has_many :followed, class_name: 'Friend', foreign_key: 'followed_id', dependent: :destroy
  has_many :following, class_name: 'Friend', foreign_key: 'following_id', dependent: :destroy
  has_many :followed_user, through: :following, source: :followed
  has_many :following_user, through: :followed, source: :following
  has_many :sns

  # ユーザーをフォローする
  def follow(user_id)
    following.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    following.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    followed_user.include?(user)
  end

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
      email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    authorization
  end

  def google_oauth2
    authorization
  end

  private

  def authorization
    sns_info = User.from_omniauth(request.env['omniauth.auth'])
    @user = sns_info[:user]

    if @user.persisted? # ユーザー情報が登録済みなので、新規登録ではなくログイン処理を行う
      sign_in_and_redirect @user, event: :authentication
    else # ユーザー情報が未登録なので、新規登録画面へ遷移する
      @sns_id = sns_info[:sns].id
      render template: 'devise/registrations/new'
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_find, only: [:show, :following, :followed]

  def show
    @evetts = Evett.where(user_id: @user.id).order('created_at DESC')
    @payments = Payment.where(user_id: @user.id).select(:evett_id).distinct

    if @user.id == current_user.id
      Payjp.api_key = ENV['PAYJP_SECRET_KEY'] # 環境変数を読み込む
      card = Card.find_by(user_id: current_user.id) # ユーザーのid情報を元に、カード情報を取得
      redirect_to new_user_card_path(current_user) and return unless card.present?

      customer = Payjp::Customer.retrieve(card.customer_token) # 先程のカード情報を元に、顧客情報を取得
      @card = customer.cards.first
      
      @following_users = @user.following_user.distinct.order('created_at DESC')
      @followed_users = @user.followed_user.distinct.order('created_at DESC')
    end
  end

  def update
    if current_user.update(user_params)
      redirect_to user_path(current_user)
    else
      redirect_to action: 'show'
    end
  end

  def following
    @users = @user.following
    render 'show_user'
  end

  def followed
    @users = @user.followed
    render 'show_user'
  end

  def search
    return nil if params[:keyword] == ''

    user = User.where('nickname LIKE ?', "%#{params[:keyword]}%")
    render json: { keyword: user }
  end

  private

  def user_params
    params.require(:user).permit(:nickname)
  end

  def user_find
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<%= render "shared/mypage-header"%>
<div class="main">
  <div class='user-evett-area'>
    <div class='evett-list', id="user-evett-list">
      <div class= 'user-evett'>
        <p>投稿済みevett一覧</p>
      <% @evetts.each do |evett|%>
        <% if evett.user.id != current_user.id && evett.share_area_id == 3 %>
        <% elsif current_user.following_user.find_by(id: @user.id) == nil && evett.share_area_id == 2 %>
        <% else %>
          <li class='evett_show_content'>
            <div class='evett_area' >
              <ul class='content_menu'>
                <% if evett.user_id == current_user.id %>
                  <li>
                    <%= link_to "編集", edit_evett_path(evett.id), method: :get %>
                  </li>
                  <li>
                    <%= link_to "削除", evett_path(evett.id), method: :delete %>
                  </li>
                <% end %>
              </ul>
              <%= link_to evett_path(evett.id) do %>
                <div class='main_content'>
                  <div class='evett_name'>
                    <h2><%= evett.name %></h2>
                  </div>
                  <div class='evett_limit_date'>
                    <% if evett.limit_date.present? %>
                      <h2>目標日：<%= evett.limit_date %></h2>
                    <% end %>
                  </div>
                  <div class='evett_price_back'>
                    <h2 class="evett_price"><%= Payment.where(evett_id: evett.id).sum(:pay) %>/<%= evett.price %>円</h2>
                    <% if Payment.where(evett_id: evett.id).sum(:pay) * 100 / evett.price >= 100 %>
                      <div id="max_percentage", class='evett_price_bar' style="width: 100%;"></div>
                    <% else %>
                      <div class='evett_price_bar' style="width: <%=  Payment.where(evett_id: evett.id).sum(:pay) * 100 / evett.price %>%;"></div>
                    <% end %>
                  </div>
                  <div class='payment_area'>
                    <%= link_to evett_payments_path(evett.id) do %>
                      <div class='evett_payment_btn'>入金</div>
                    <% end %>
                    <div class='payment_percentage'>
                      <% unless Payment.where(evett_id: evett.id).sum(:pay) == 0 %>
                        <h2><%=  Payment.where(evett_id: evett.id).sum(:pay) * 100 / evett.price %>%</h2>
                      <% else %>
                        <h2>0%</h2>
                      <% end %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </li>
        <% end %>
      <% end %>
      </div>
      <div class='user-pay-evett'>
        <p>入金済みevett一覧</p>
      <% @payments.each do |pay| %>
        <% if pay.evett.user.id != current_user.id && pay.evett.share_area_id == 3 %>
        <% elsif current_user.following_user.find_by(id: @user.id) == nil && pay.evett.share_area_id == 2 %>
        <% else %>
          <li class='evett_show_content'>
            <div class='evett_area' >
              <ul class='content_menu'>
                <% if pay.evett.user_id == current_user.id %>
                  <li>
                    <%= link_to "編集", edit_evett_path(pay.evett.id), method: :get %>
                  </li>
                  <li>
                    <%= link_to "削除", evett_path(pay.evett.id), method: :delete %>
                  </li>
                <% end %>
              </ul>
              <%= link_to evett_path(pay.evett.id) do %>
                <div class='main_content'>
                  <div class='evett_name'>
                    <h2><%= pay.evett.name %></h2>
                  </div>
                  <div class='evett_limit_date'>
                    <% if pay.evett.limit_date.present? %>
                      <h2>目標日：<%= pay.evett.limit_date %></h2>
                    <% end %>
                  </div>
                  <div class='evett_price_back'>
                    <h2 class="evett_price"><%= Payment.where(evett_id: pay.evett.id).sum(:pay) %>/<%= pay.evett.price %>円</h2>
                    <% if Payment.where(evett_id: pay.evett.id).sum(:pay) * 100 / pay.evett.price >= 100 %>
                      <div id="max_percentage", class='evett_price_bar' style="width: 100%;"></div>
                    <% else %>
                      <div class='evett_price_bar' style="width: <%=  Payment.where(evett_id: pay.evett.id).sum(:pay) * 100 / pay.evett.price %>%;"></div>
                    <% end %>
                  </div>
                  <div class='payment_area'>
                    <%= link_to evett_payments_path(pay.evett.id) do %>
                      <div class='evett_payment_btn'>入金</div>
                    <% end %>
                    <div class='payment_percentage'>
                      <% unless Payment.where(evett_id: pay.evett.id).sum(:pay) == 0 %>
                        <h2><%=  Payment.where(evett_id: pay.evett.id).sum(:pay) * 100 / pay.evett.price %>%</h2>
                      <% else %>
                        <h2>0%</h2>
                      <% end %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </li>
        <% end %>
      <% end %>
    </div>
  </div>

    <% if @user.id == current_user.id %>
      <div class="user_area", id="user-info-area">
        <div class="Card_area">
          <div class="Card__title">
            <h2>カード情報</h2>
          </div>
          <div class="Card_info">
            【カード番号】
            <br>
            <%= "**** **** **** " + @card[:last4] %>
            <%# カード番号の下4桁を取得 %>

            <br>
            【有効期限】
            <br>
            <%= @card[:exp_month] %>
            <%# 有効期限の「月」を取得 %>
            /
            <%= @card[:exp_year] %><br>
            <%# 有効期限の「年」を取得 %>
          </div>
          <div class="new-card-link">
            <%= link_to '新しいカード情報を登録する', new_user_card_path(current_user)%>
          </div>
        </div>
        <%= render 'friends/follow', user: @user %>
        <%= form_with(url: search_users_path, local: true, method: :get, id: "search-form") do |f| %>
          <%= f.text_field :nickname, placeholder: "ユーザーを検索する", id: "search-input" %>
          <div id="result"></div>
          <div>＊enterキーを押さないで下さい</div>
        <% end %>
      </div>
      <div class="user_area", id="user-rank-area">
        <div class="Card_area">
          <div class="Card__title">
            <h2>ランク情報</h2>
          </div>
          <div class="Card_info">
            <%if @user.rank_id == 1%>
              <div>ブロンズランク</div>
            <% elsif @user.rank_id == 2 %>
              <div>シルバーランク</div>
            <% elsif @user.rank_id == 3 %>
              <div>ゴールドランク</div>
            <% end %>
          </div>
          <div class="new-card-link">
            ランク変更はこちらから
          </div>
        </div>
        <div class="Card_area">
          <div class="Card__title">
            <%if @user.rank_id == 1%>
              <div>ブロンズランク</div>
            <% elsif @user.rank_id == 2 %>
              <div>シルバーランク</div>
            <% elsif @user.rank_id == 3 %>
              <div>ゴールドランク</div>
            <% end %>
          </div>
          <div class="Card_info">
            <div>
              <p>投稿数：
              <%if @user.rank_id == 1%>
                5個</p>
              <% elsif @user.rank_id == 2 %>
                25個</p>
              <% elsif @user.rank_id == 3 %>
                50個</p>
              <% end %>
            </div>
            <div>
              <p>フォロー人数：
              <%if @user.rank_id == 1%>
                10人</p>
              <% elsif @user.rank_id == 2 %>
                30人</p>
              <% elsif @user.rank_id == 3 %>
                100人</p>
              <% end %>
            </div>
          </div>
          <div class="new-card-link">
            ランク変更はこちらから
          </div>
        </div>
        <%= form_with(url: search_users_path, local: true, method: :get, id: "search-form") do |f| %>
          <%= f.text_field :nickname, placeholder: "ユーザーを検索する", id: "search-input" %>
          <div id="result"></div>
          <div>＊enterキーを押さないで下さい</div>
        <% end %>
      </div>
    <% end %>
</div>

<%= render "shared/footer" %>