config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  get 'users/show'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: "evetts#index"
  resources :evetts do
    resources :payments, only: [:index, :create]
  end
  resources :users, only: [:show, :update] do
    resources :cards, only: [:new, :create]
    get 'followings', to: 'freinds#followings', as: 'followings'
    get 'followeds', to: 'freinds#followeds', as: 'followeds'
    resource :friend, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  attr_accessor :card_token

  validates :card_token, presence: true
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def new
    @card = Card.new
  end

  def create
    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    customer = Payjp::Customer.create(card: params[:card_token])
    @card = Card.new(
      user_id: current_user.id,
      customer_token: customer.id,
      card_token: params[:card_token]
    )
    if @card.valid?
      @card.save
      redirect_to user_path(current_user.id)
    else
      render 'new'
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/new.html.erb
<div class="main">
  <div class='transaction-contents'>
    <div class='logo'><%= link_to "Evett", root_path %></div>
      <div class='transaction-main'>
        <%= form_with model: @card, url: user_cards_path, id: 'charge-form', class: 'transaction-form-wrap', local: true do |f| %>
          <%= render 'shared/error_messages', model: f.object %>
        <%# カード情報の入力 %>
          <div class='credit-card-form' id='mycard_page'>
            <h1 class='info-input-haedline'>
              クレジットカード情報入力
            </h1>
            <div class="form-group">
              <div class='form-text-wrap'>
                <label class="form-text">カード情報</label>
                <span class="indispensable">必須</span>
              </div>
              <%= f.text_field :number, class:"input-default", id:"card-number", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
              <div class='available-card'>
                <%= image_tag 'card-visa.gif', class: 'card-logo'%>
                <%= image_tag 'card-mastercard.gif', class: 'card-logo'%>
                <%= image_tag 'card-jcb.gif', class: 'card-logo'%>
                <%= image_tag 'card-amex.gif', class: 'card-logo'%>
              </div>
            </div>
            <div class="form-group">
              <div class='form-text-wrap'>
                <label class="form-text">有効期限</label>
                <span class="indispensable">必須</span>
              </div>
              <div class='input-expiration-date-wrap'>
                <%= f.text_area :exp_month, class:"input-expiration-date", id:"card-exp-month", placeholder:"例)3" %>
                <p>月</p>
                <%= f.text_area :exp_year, class:"input-expiration-date", id:"card-exp-year", placeholder:"例)23" %>
                <p>年</p>
              </div>
            </div>
            <div class="form-group">
              <div class='form-text-wrap'>
                <label class="form-text">セキュリティコード</label>
                <span class="indispensable">必須</span>
              </div>
              <%= f.text_field :cvc, class:"input-default", id:"card-cvc", placeholder:"カード背面4桁もしくは3桁の番号", maxlength:"4" %>
            </div>
          </div>
          <%# /カード情報の入力 %>
      <div class='payment-btn'>
        <%= f.submit "購入" ,class:"payment-red-btn", id:"button" %>
      </div>
      <% end %>
    </div>
  </div>
</div>
<%= render "shared/footer" %>